MERGE [ParamCrm_Cockpit].[dbo].[Account] AS TARGET
USING (
    SELECT *
    FROM [1886662b0a1847a7973577f52892968fdb].[dbo].[Account]
	Where DeletedOn is null
) AS SOURCE
ON TARGET.Id = SOURCE.Id COLLATE Turkish_CI_AS

WHEN MATCHED THEN
    UPDATE SET
        TARGET.Name = SOURCE.Name,
        TARGET.Code = SOURCE.Code,
        TARGET.Title = SOURCE.Title,
        TARGET.Type = SOURCE.Type,
        TARGET.ParentAccountId = SOURCE.ParentAccountId,
        TARGET.OwnerId = SOURCE.OwnerId,
        TARGET.TerritoryId = SOURCE.TerritoryId,
        TARGET.State = SOURCE.State,
        TARGET.DefaultDiscount = SOURCE.DefaultDiscount,
        TARGET.DefaultCurrency = SOURCE.DefaultCurrency,
        TARGET.IdentificationNumber = SOURCE.IdentificationNumber,
        TARGET.SurName = SOURCE.SurName,
        TARGET.CellPhone = SOURCE.CellPhone,
        TARGET.Phone = SOURCE.Phone,
        TARGET.TaxOffice = SOURCE.TaxOffice,
        TARGET.TaxNumber = SOURCE.TaxNumber,
        TARGET.Email = SOURCE.Email,
        TARGET.DealerId = SOURCE.DealerId,
        TARGET.AccountGroupId = SOURCE.AccountGroupId,
        TARGET.AccountAdditionalGroupId = SOURCE.AccountAdditionalGroupId,
        TARGET.CurrencyRateType = SOURCE.CurrencyRateType,
        TARGET.IsVATExempt = SOURCE.IsVATExempt,
        TARGET.WebSite = SOURCE.WebSite,
        TARGET.Sector = SOURCE.Sector,
        TARGET.ActivitySummary = SOURCE.ActivitySummary,
        TARGET.LastTouchDate = CAST(SOURCE.LastTouchDate AS date),
        TARGET.SignBoardName = SOURCE.SignBoardName,
        TARGET.Emplooyes = SOURCE.Emplooyes,
        TARGET.LeadSource = SOURCE.LeadSource,
        TARGET.AccountNumber = SOURCE.AccountNumber,
        TARGET.Instagram = SOURCE.Instagram,
        TARGET.Fax = SOURCE.Fax,
        TARGET.RelatedDepartment = SOURCE.RelatedDepartment,
        TARGET.ParamBusinessCardNo = SOURCE.ParamBusinessCardNo,
        TARGET.ReferenceCode = SOURCE.ReferenceCode,
        TARGET.MonthlyTurnoverLevel = SOURCE.MonthlyTurnoverLevel,
        TARGET.RivalFirmId = SOURCE.RivalFirmId,
        TARGET.AccountNameSurname = SOURCE.AccountNameSurname,
        TARGET.MonthlyTurnoverLevelTR = SOURCE.MonthlyTurnoverLevelTR,
        TARGET.SectorTR = SOURCE.SectorTR,
        TARGET.FirstCreatedDate = CAST(SOURCE.FirstCreatedDate AS date),
        TARGET.FirstCreatedByName = SOURCE.FirstCreatedByName,
        TARGET.Email2 = SOURCE.Email2,
        TARGET.Email3 = SOURCE.Email3,
        TARGET.BusinessPartnerId = SOURCE.BusinessPartnerId,
        TARGET.UsedERP = SOURCE.UsedERP,
        TARGET.IsInvoiceGenerated = SOURCE.IsInvoiceGenerated,
        TARGET.IsTrainingProvided = SOURCE.IsTrainingProvided,
        TARGET.IsContractReceived = SOURCE.IsContractReceived,
        TARGET.NumberOfEmployees = SOURCE.NumberOfEmployees,
        TARGET.NumberOfDealer = SOURCE.NumberOfDealer,
        TARGET.NumberOfWorkingBank = SOURCE.NumberOfWorkingBank,
        TARGET.ENumberOfGroupComplaints = SOURCE.ENumberOfGroupComplaints,
        TARGET.CapitalSize = SOURCE.CapitalSize,
        TARGET.AccountGroupInfo = SOURCE.AccountGroupInfo,
        TARGET.CompanyAge = SOURCE.CompanyAge,
        TARGET.InRefCode = SOURCE.InRefCode,
        TARGET.City = SOURCE.City,
        TARGET.LeadSourceNextGenId = SOURCE.LeadSourceNextGenId,
        TARGET.IsSpecialField = SOURCE.IsSpecialField,
        TARGET.IsoThousandRank = SOURCE.IsoThousandRank,
        TARGET.CommunicationInfo = SOURCE.CommunicationInfo,
        TARGET.CreditUsageCountForLastMonth = SOURCE.CreditUsageCountForLastMonth,
        TARGET.CreditUsageCountForLastThreeMonth = SOURCE.CreditUsageCountForLastThreeMonth,
        TARGET.CreditUsageCountForYear = SOURCE.CreditUsageCountForYear,
        TARGET.FieldSalesRepresentativeId = SOURCE.FieldSalesRepresentativeId,
        TARGET.TPOutReferenceCode = SOURCE.TPOutReferenceCode,
        TARGET.CountrySapId = SOURCE.CountrySapId,
        TARGET.CountryRegionSapId = SOURCE.CountryRegionSapId,
        TARGET.CurrencySapId = SOURCE.CurrencySapId,
        TARGET.CustomerAccountGroupSapId = SOURCE.CustomerAccountGroupSapId,
        TARGET.LanguageSapId = SOURCE.LanguageSapId,
        TARGET.PaymentTermSapId = SOURCE.PaymentTermSapId,
        TARGET.SalesOfficeSapId = SOURCE.SalesOfficeSapId,
        TARGET.TaxClassificationSapId = SOURCE.TaxClassificationSapId,
        TARGET.SAPOutReferenceCode = SOURCE.SAPOutReferenceCode,
        TARGET.IBAN = SOURCE.IBAN,
        TARGET.BankCountryId = SOURCE.BankCountryId,
        TARGET.BankCurrencySapId = SOURCE.BankCurrencySapId,
        TARGET.AccountHolderName = SOURCE.AccountHolderName,
        TARGET.OtherUsedERP = SOURCE.OtherUsedERP,
        TARGET.EDocumentType = SOURCE.EDocumentType,
        TARGET.Location_Latitude = SOURCE.Location_Latitude,
        TARGET.Location_Longitude = SOURCE.Location_Longitude,
        TARGET.CreditLimit_Amount = SOURCE.CreditLimit_Amount,
        TARGET.CreditLimit_Currency = SOURCE.CreditLimit_Currency,
        TARGET.RiskLimit_Amount = SOURCE.RiskLimit_Amount,
        TARGET.RiskLimit_Currency = SOURCE.RiskLimit_Currency,
        TARGET.CreditUsageAmountForLastMonth_Amount = SOURCE.CreditUsageAmountForLastMonth_Amount,
        TARGET.CreditUsageAmountForLastMonth_Currency = SOURCE.CreditUsageAmountForLastMonth_Currency,
        TARGET.CreditUsageAmountForLastThreeMonths_Amount = SOURCE.CreditUsageAmountForLastThreeMonths_Amount,
        TARGET.CreditUsageAmountForLastThreeMonths_Currency = SOURCE.CreditUsageAmountForLastThreeMonths_Currency,
        TARGET.CreditUsageAmountForYear_Amount = SOURCE.CreditUsageAmountForYear_Amount,
        TARGET.CreditUsageAmountForYear_Currency = SOURCE.CreditUsageAmountForYear_Currency,
        TARGET._SyncedAt = GETUTCDATE()

WHEN NOT MATCHED BY SOURCE THEN
    DELETE
WHEN NOT MATCHED THEN
    INSERT (
        Id, Name, Code, Title, Type, ParentAccountId, OwnerId,
        TerritoryId, State, DefaultDiscount, DefaultCurrency,
        IdentificationNumber, SurName, CellPhone, Phone,
        TaxOffice, TaxNumber, Email, DealerId,
        AccountGroupId, AccountAdditionalGroupId,
        CurrencyRateType, IsVATExempt, WebSite, Sector,
        ActivitySummary, LastTouchDate, SignBoardName,
        Emplooyes, LeadSource, AccountNumber, Instagram,
        Fax, RelatedDepartment, ParamBusinessCardNo,
        ReferenceCode, MonthlyTurnoverLevel, RivalFirmId,
        AccountNameSurname, MonthlyTurnoverLevelTR, SectorTR,
        FirstCreatedDate, FirstCreatedByName,
        Email2, Email3, BusinessPartnerId,
        UsedERP, IsInvoiceGenerated, IsTrainingProvided,
        IsContractReceived, NumberOfEmployees, NumberOfDealer,
        NumberOfWorkingBank, ENumberOfGroupComplaints,
        CapitalSize, AccountGroupInfo, CompanyAge,
        InRefCode, City, LeadSourceNextGenId,
        IsSpecialField, IsoThousandRank, CommunicationInfo,
        CreditUsageCountForLastMonth,
        CreditUsageCountForLastThreeMonth,
        CreditUsageCountForYear,
        FieldSalesRepresentativeId,
        TPOutReferenceCode,
        CountrySapId, CountryRegionSapId,
        CurrencySapId, CustomerAccountGroupSapId,
        LanguageSapId, PaymentTermSapId,
        SalesOfficeSapId, TaxClassificationSapId,
        SAPOutReferenceCode, IBAN,
        BankCountryId, BankCurrencySapId,
        AccountHolderName, OtherUsedERP,
        EDocumentType,
        Location_Latitude, Location_Longitude,
        CreditLimit_Amount, CreditLimit_Currency,
        RiskLimit_Amount, RiskLimit_Currency,
        CreditUsageAmountForLastMonth_Amount,
        CreditUsageAmountForLastMonth_Currency,
        CreditUsageAmountForLastThreeMonths_Amount,
        CreditUsageAmountForLastThreeMonths_Currency,
        CreditUsageAmountForYear_Amount,
        CreditUsageAmountForYear_Currency
    )
    VALUES (
        SOURCE.Id, SOURCE.Name, SOURCE.Code, SOURCE.Title,
        SOURCE.Type, SOURCE.ParentAccountId, SOURCE.OwnerId,
        SOURCE.TerritoryId, SOURCE.State, SOURCE.DefaultDiscount,
        SOURCE.DefaultCurrency, SOURCE.IdentificationNumber,
        SOURCE.SurName, SOURCE.CellPhone, SOURCE.Phone,
        SOURCE.TaxOffice, SOURCE.TaxNumber, SOURCE.Email,
        SOURCE.DealerId, SOURCE.AccountGroupId,
        SOURCE.AccountAdditionalGroupId,
        SOURCE.CurrencyRateType, SOURCE.IsVATExempt,
        SOURCE.WebSite, SOURCE.Sector,
        SOURCE.ActivitySummary,
        CAST(SOURCE.LastTouchDate AS date),
        SOURCE.SignBoardName, SOURCE.Emplooyes,
        SOURCE.LeadSource, SOURCE.AccountNumber,
        SOURCE.Instagram, SOURCE.Fax,
        SOURCE.RelatedDepartment,
        SOURCE.ParamBusinessCardNo,
        SOURCE.ReferenceCode,
        SOURCE.MonthlyTurnoverLevel,
        SOURCE.RivalFirmId,
        SOURCE.AccountNameSurname,
        SOURCE.MonthlyTurnoverLevelTR,
        SOURCE.SectorTR,
        CAST(SOURCE.FirstCreatedDate AS date),
        SOURCE.FirstCreatedByName,
        SOURCE.Email2, SOURCE.Email3,
        SOURCE.BusinessPartnerId,
        SOURCE.UsedERP,
        SOURCE.IsInvoiceGenerated,
        SOURCE.IsTrainingProvided,
        SOURCE.IsContractReceived,
        SOURCE.NumberOfEmployees,
        SOURCE.NumberOfDealer,
        SOURCE.NumberOfWorkingBank,
        SOURCE.ENumberOfGroupComplaints,
        SOURCE.CapitalSize,
        SOURCE.AccountGroupInfo,
        SOURCE.CompanyAge,
        SOURCE.InRefCode,
        SOURCE.City,
        SOURCE.LeadSourceNextGenId,
        SOURCE.IsSpecialField,
        SOURCE.IsoThousandRank,
        SOURCE.CommunicationInfo,
        SOURCE.CreditUsageCountForLastMonth,
        SOURCE.CreditUsageCountForLastThreeMonth,
        SOURCE.CreditUsageCountForYear,
        SOURCE.FieldSalesRepresentativeId,
        SOURCE.TPOutReferenceCode,
        SOURCE.CountrySapId,
        SOURCE.CountryRegionSapId,
        SOURCE.CurrencySapId,
        SOURCE.CustomerAccountGroupSapId,
        SOURCE.LanguageSapId,
        SOURCE.PaymentTermSapId,
        SOURCE.SalesOfficeSapId,
        SOURCE.TaxClassificationSapId,
        SOURCE.SAPOutReferenceCode,
        SOURCE.IBAN,
        SOURCE.BankCountryId,
        SOURCE.BankCurrencySapId,
        SOURCE.AccountHolderName,
        SOURCE.OtherUsedERP,
        SOURCE.EDocumentType,
        SOURCE.Location_Latitude,
        SOURCE.Location_Longitude,
        SOURCE.CreditLimit_Amount,
        SOURCE.CreditLimit_Currency,
        SOURCE.RiskLimit_Amount,
        SOURCE.RiskLimit_Currency,
        SOURCE.CreditUsageAmountForLastMonth_Amount,
        SOURCE.CreditUsageAmountForLastMonth_Currency,
        SOURCE.CreditUsageAmountForLastThreeMonths_Amount,
        SOURCE.CreditUsageAmountForLastThreeMonths_Currency,
        SOURCE.CreditUsageAmountForYear_Amount,
        SOURCE.CreditUsageAmountForYear_Currency
    );