MERGE [ParamCrm_Cockpit].[dbo].[CalenderEvent] AS TARGET
USING (
    SELECT
        Id,
        OwnerId,
        Subject,
        Type,
        Description,
        CONVERT(nvarchar(50), StartDate, 127) AS StartDate,
        CONVERT(nvarchar(50), FinishDate, 127) AS FinishDate,
        Location,
        AccountId,
        LeadId,
        ContactId,
        CompanyId,
        ParentEventId,
        CAST(IsAllDay AS int) AS IsAllDay,
        CAST(IsRepeat AS int) AS IsRepeat,
        CAST(IsReminderSet AS int) AS IsReminderSet,
        CAST(IsNewAccount AS int) AS IsNewAccount,
        RepeatPattern,
        RepeatEvery,
        MonthForRepeatOnYearly,
        EndRepeat,
        AfterOccurrenceCount,
        TimeBeforeEvent,
        RepeatEveryHours,
        RepeatEveryDays,
        RepeatOnMonthly,
        RepeatOnYearly,
        CONVERT(nvarchar(50), EndRepeatDate, 127) AS EndRepeatDate,
        Status,
        RecurrenceRule,
        RecurrenceException,
        ParticipantType,
        SubjectType,
        CAST(ExcludeWeekends AS int) AS ExcludeWeekends,
        FirstCreatedBy,
        CONVERT(nvarchar(50), FirstCreatedDate, 127) AS FirstCreatedDate,
        EventEnvironment,
        CalendarEventResultId,
        GoogleCalendarEventCreatedMail,
        SubjectTypeTr,
        TypeTr,
        StatusTr,
        EventEnvironmentTr,
        ParticipantTypeTr
    FROM [1886662b0a1847a7973577f52892968fdb].[dbo].[CalenderEvent]
    WHERE DeletedOn IS NULL and CompanyId = '4f1687e4-f282-4601-a3cc-ef612e00c3e4'
) AS SOURCE
ON TARGET.Id = SOURCE.Id COLLATE Turkish_CI_AS
WHEN NOT MATCHED BY SOURCE THEN
    DELETE
WHEN MATCHED THEN
UPDATE SET
    TARGET.OwnerId = SOURCE.OwnerId,
    TARGET.Subject = SOURCE.Subject,
    TARGET.Type = SOURCE.Type,
    TARGET.Description = SOURCE.Description,
    TARGET.StartDate = SOURCE.StartDate,
    TARGET.FinishDate = SOURCE.FinishDate,
    TARGET.Location = SOURCE.Location,
    TARGET.AccountId = SOURCE.AccountId,
    TARGET.LeadId = SOURCE.LeadId,
    TARGET.ContactId = SOURCE.ContactId,
    TARGET.CompanyId = SOURCE.CompanyId,
    TARGET.ParentEventId = SOURCE.ParentEventId,
    TARGET.IsAllDay = SOURCE.IsAllDay,
    TARGET.IsRepeat = SOURCE.IsRepeat,
    TARGET.IsReminderSet = SOURCE.IsReminderSet,
    TARGET.IsNewAccount = SOURCE.IsNewAccount,
    TARGET.RepeatPattern = SOURCE.RepeatPattern,
    TARGET.RepeatEvery = SOURCE.RepeatEvery,
    TARGET.MonthForRepeatOnYearly = SOURCE.MonthForRepeatOnYearly,
    TARGET.EndRepeat = SOURCE.EndRepeat,
    TARGET.AfterOccurrenceCount = SOURCE.AfterOccurrenceCount,
    TARGET.TimeBeforeEvent = SOURCE.TimeBeforeEvent,
    TARGET.RepeatEveryHours = SOURCE.RepeatEveryHours,
    TARGET.RepeatEveryDays = SOURCE.RepeatEveryDays,
    TARGET.RepeatOnMonthly = SOURCE.RepeatOnMonthly,
    TARGET.RepeatOnYearly = SOURCE.RepeatOnYearly,
    TARGET.EndRepeatDate = SOURCE.EndRepeatDate,
    TARGET.Status = SOURCE.Status,
    TARGET.RecurrenceRule = SOURCE.RecurrenceRule,
    TARGET.RecurrenceException = SOURCE.RecurrenceException,
    TARGET.ParticipantType = SOURCE.ParticipantType,
    TARGET.SubjectType = SOURCE.SubjectType,
    TARGET.ExcludeWeekends = SOURCE.ExcludeWeekends,
    TARGET.FirstCreatedBy = SOURCE.FirstCreatedBy,
    TARGET.FirstCreatedDate = SOURCE.FirstCreatedDate,
    TARGET.EventEnvironment = SOURCE.EventEnvironment,
    TARGET.CalendarEventResultId = SOURCE.CalendarEventResultId,
    TARGET.GoogleCalendarEventCreatedMail = SOURCE.GoogleCalendarEventCreatedMail,
    TARGET.SubjectTypeTr = SOURCE.SubjectTypeTr,
    TARGET.TypeTr = SOURCE.TypeTr,
    TARGET.StatusTr = SOURCE.StatusTr,
    TARGET.EventEnvironmentTr = SOURCE.EventEnvironmentTr,
    TARGET.ParticipantTypeTr = SOURCE.ParticipantTypeTr

WHEN NOT MATCHED THEN
INSERT (
    Id, OwnerId, Subject, Type, Description,
    StartDate, FinishDate, Location,
    AccountId, LeadId, ContactId, CompanyId, ParentEventId,
    IsAllDay, IsRepeat, IsReminderSet, IsNewAccount,
    RepeatPattern, RepeatEvery, MonthForRepeatOnYearly,
    EndRepeat, AfterOccurrenceCount, TimeBeforeEvent,
    RepeatEveryHours, RepeatEveryDays,
    RepeatOnMonthly, RepeatOnYearly,
    EndRepeatDate, Status,
    RecurrenceRule, RecurrenceException,
    ParticipantType, SubjectType, ExcludeWeekends,
    FirstCreatedBy, FirstCreatedDate,
    EventEnvironment, CalendarEventResultId,
    GoogleCalendarEventCreatedMail,
    SubjectTypeTr, TypeTr, StatusTr,
    EventEnvironmentTr, ParticipantTypeTr
)
VALUES (
    SOURCE.Id, SOURCE.OwnerId, SOURCE.Subject, SOURCE.Type, SOURCE.Description,
    SOURCE.StartDate, SOURCE.FinishDate, SOURCE.Location,
    SOURCE.AccountId, SOURCE.LeadId, SOURCE.ContactId, SOURCE.CompanyId, SOURCE.ParentEventId,
    SOURCE.IsAllDay, SOURCE.IsRepeat, SOURCE.IsReminderSet, SOURCE.IsNewAccount,
    SOURCE.RepeatPattern, SOURCE.RepeatEvery, SOURCE.MonthForRepeatOnYearly,
    SOURCE.EndRepeat, SOURCE.AfterOccurrenceCount, SOURCE.TimeBeforeEvent,
    SOURCE.RepeatEveryHours, SOURCE.RepeatEveryDays,
    SOURCE.RepeatOnMonthly, SOURCE.RepeatOnYearly,
    SOURCE.EndRepeatDate, SOURCE.Status,
    SOURCE.RecurrenceRule, SOURCE.RecurrenceException,
    SOURCE.ParticipantType, SOURCE.SubjectType, SOURCE.ExcludeWeekends,
    SOURCE.FirstCreatedBy, SOURCE.FirstCreatedDate,
    SOURCE.EventEnvironment, SOURCE.CalendarEventResultId,
    SOURCE.GoogleCalendarEventCreatedMail,
    SOURCE.SubjectTypeTr, SOURCE.TypeTr, SOURCE.StatusTr,
    SOURCE.EventEnvironmentTr, SOURCE.ParticipantTypeTr
);