MERGE [ParamCrm_Cockpit].[dbo].[CrmOrder] AS TARGET
USING (
    SELECT
        CAST(Id AS nvarchar(450)) AS Id,
        CAST(QuoteId AS nvarchar(max)) AS QuoteId,
        CAST(AccountId AS nvarchar(max)) AS AccountId,
        CAST(ProposalOwnerId AS nvarchar(max)) AS ProposalOwnerId,
        CAST(WarehouseId AS nvarchar(max)) AS WarehouseId,
        CAST(TeamId AS nvarchar(max)) AS TeamId,
        CAST(TeamCreatedById AS nvarchar(max)) AS TeamCreatedById,
        CAST(CompanyId AS nvarchar(max)) AS CompanyId,
        CAST(StockId AS nvarchar(max)) AS StockId,
        CAST(SpecialCodeId AS nvarchar(max)) AS SpecialCodeId,
        CAST(DistributionChannelSapId AS nvarchar(max)) AS DistributionChannelSapId,
        CAST(DivisionSapId AS nvarchar(max)) AS DivisionSapId,
        CAST(SalesDocumentTypeSapId AS nvarchar(max)) AS SalesDocumentTypeSapId,
        CAST(SalesOrganizationSapId AS nvarchar(max)) AS SalesOrganizationSapId,
        CAST(SalesPaymentTermSapId AS nvarchar(max)) AS SalesPaymentTermSapId,
        CAST(CrmSalesOfficeSapId AS nvarchar(max)) AS CrmSalesOfficeSapId,
        CAST(CurrencySapId AS nvarchar(max)) AS CurrencySapId,
        CAST(SalesGroupSapId AS nvarchar(max)) AS SalesGroupSapId,
        CAST(ContractId AS nvarchar(max)) AS ContractId,

        PaymentType,
        PaymentTypeTime,
        DeliveryType,
        DeliveryTypeTime,
        SubTotalAlternativeCurrency,
        SubTotalDiscountType,
        Status,

        CAST(IsVATExempt AS int) AS IsVATExempt,
        CAST(IsEligibleForNetsisIntegration AS int) AS IsEligibleForNetsisIntegration,
        CAST(IsEligibleForSapIntegration AS int) AS IsEligibleForSapIntegration,
        CAST(IsDeletedFromBackend AS int) AS IsDeletedFromBackend,

        CONVERT(nvarchar(max), ExpirationDate, 126) AS ExpirationDate,
        CONVERT(nvarchar(max), DeliveryDate, 126) AS DeliveryDate,
        CONVERT(nvarchar(max), CreateOrderDate, 126) AS CreateOrderDate,
        CONVERT(nvarchar(max), PlannedInvoiceDate, 126) AS PlannedInvoiceDate,
        CONVERT(nvarchar(max), InvoiceDate, 126) AS InvoiceDate,

        SubTotalDiscount,
        DeliveryTime,
        PaymentTime,
        CAST(AlternativeCurrencyRate AS float) AS AlternativeCurrencyRate,
        SubTotalDiscountAmount,
        TotalDiscountRate,

        CAST(NetSubTotalLocalCurrency_Amount AS float) AS NetSubTotalLocalCurrency_Amount,
        CAST(NetSubTotalLocalCurrency_Currency AS nvarchar(max)) AS NetSubTotalLocalCurrency_Currency,

        CAST(TotalNetAmountLocalCurrency_Amount AS float) AS TotalNetAmountLocalCurrency_Amount,
        CAST(TotalNetAmountLocalCurrency_Currency AS nvarchar(max)) AS TotalNetAmountLocalCurrency_Currency,

        CAST(TotalAmountWithTaxLocalCurrency_Amount AS float) AS TotalAmountWithTaxLocalCurrency_Amount,
        CAST(TotalAmountWithTaxLocalCurrency_Currency AS nvarchar(max)) AS TotalAmountWithTaxLocalCurrency_Currency,

        CAST(TotalProfitAmount_Amount AS float) AS TotalProfitAmount_Amount,
        CAST(TotalProfitAmount_Currency AS nvarchar(max)) AS TotalProfitAmount_Currency,

        CAST(NetSubTotalAlternativeCurrency_Amount AS float) AS NetSubTotalAlternativeCurrency_Amount,
        CAST(NetSubTotalAlternativeCurrency_Currency AS nvarchar(max)) AS NetSubTotalAlternativeCurrency_Currency,

        CAST(TotalNetAmountAlternativeCurrency_Amount AS float) AS TotalNetAmountAlternativeCurrency_Amount,
        CAST(TotalNetAmountAlternativeCurrency_Currency AS nvarchar(max)) AS TotalNetAmountAlternativeCurrency_Currency,

        CAST(TotalAmountWithTaxAlternativeCurrency_Amount AS float) AS TotalAmountWithTaxAlternativeCurrency_Amount,
        CAST(TotalAmountWithTaxAlternativeCurrency_Currency AS nvarchar(max)) AS TotalAmountWithTaxAlternativeCurrency_Currency,

        CAST(TotalProfitAmountAlternativeCurrency_Amount AS float) AS TotalProfitAmountAlternativeCurrency_Amount,
        CAST(TotalProfitAmountAlternativeCurrency_Currency AS nvarchar(max)) AS TotalProfitAmountAlternativeCurrency_Currency,

        ReferenceCode,
        InRefCode,
        CustomerOrderNumber,
        TPOutReferenceCode,
        SAPOutReferenceCode,
        ItemNo,
        CrmOrderNotes,
        Name,
        SerialNumber

    FROM [1886662b0a1847a7973577f52892968fdb].[dbo].[CrmOrder]
    WHERE DeletedOn IS NULL and CompanyId = '4f1687e4-f282-4601-a3cc-ef612e00c3e4'
) AS SOURCE
ON TARGET.Id = SOURCE.Id COLLATE Turkish_CI_AS
WHEN NOT MATCHED BY SOURCE THEN
    DELETE
WHEN MATCHED THEN
UPDATE SET
    TARGET.QuoteId = SOURCE.QuoteId,
    TARGET.AccountId = SOURCE.AccountId,
    TARGET.ProposalOwnerId = SOURCE.ProposalOwnerId,
    TARGET.WarehouseId = SOURCE.WarehouseId,
    TARGET.TeamId = SOURCE.TeamId,
    TARGET.TeamCreatedById = SOURCE.TeamCreatedById,
    TARGET.CompanyId = SOURCE.CompanyId,
    TARGET.StockId = SOURCE.StockId,
    TARGET.SpecialCodeId = SOURCE.SpecialCodeId,
    TARGET.DistributionChannelSapId = SOURCE.DistributionChannelSapId,
    TARGET.DivisionSapId = SOURCE.DivisionSapId,
    TARGET.SalesDocumentTypeSapId = SOURCE.SalesDocumentTypeSapId,
    TARGET.SalesOrganizationSapId = SOURCE.SalesOrganizationSapId,
    TARGET.SalesPaymentTermSapId = SOURCE.SalesPaymentTermSapId,
    TARGET.CrmSalesOfficeSapId = SOURCE.CrmSalesOfficeSapId,
    TARGET.CurrencySapId = SOURCE.CurrencySapId,
    TARGET.SalesGroupSapId = SOURCE.SalesGroupSapId,
    TARGET.ContractId = SOURCE.ContractId,

    TARGET.PaymentType = SOURCE.PaymentType,
    TARGET.PaymentTypeTime = SOURCE.PaymentTypeTime,
    TARGET.DeliveryType = SOURCE.DeliveryType,
    TARGET.DeliveryTypeTime = SOURCE.DeliveryTypeTime,
    TARGET.SubTotalAlternativeCurrency = SOURCE.SubTotalAlternativeCurrency,
    TARGET.SubTotalDiscountType = SOURCE.SubTotalDiscountType,
    TARGET.Status = SOURCE.Status,

    TARGET.IsVATExempt = SOURCE.IsVATExempt,
    TARGET.IsEligibleForNetsisIntegration = SOURCE.IsEligibleForNetsisIntegration,
    TARGET.IsEligibleForSapIntegration = SOURCE.IsEligibleForSapIntegration,
    TARGET.IsDeletedFromBackend = SOURCE.IsDeletedFromBackend,

    TARGET.ExpirationDate = SOURCE.ExpirationDate,
    TARGET.DeliveryDate = SOURCE.DeliveryDate,
    TARGET.CreateOrderDate = SOURCE.CreateOrderDate,
    TARGET.PlannedInvoiceDate = SOURCE.PlannedInvoiceDate,
    TARGET.InvoiceDate = SOURCE.InvoiceDate,

    TARGET.SubTotalDiscount = SOURCE.SubTotalDiscount,
    TARGET.DeliveryTime = SOURCE.DeliveryTime,
    TARGET.PaymentTime = SOURCE.PaymentTime,
    TARGET.AlternativeCurrencyRate = SOURCE.AlternativeCurrencyRate,
    TARGET.SubTotalDiscountAmount = SOURCE.SubTotalDiscountAmount,
    TARGET.TotalDiscountRate = SOURCE.TotalDiscountRate,

    TARGET.NetSubTotalLocalCurrency_Amount = SOURCE.NetSubTotalLocalCurrency_Amount,
    TARGET.NetSubTotalLocalCurrency_Currency = SOURCE.NetSubTotalLocalCurrency_Currency,
    TARGET.TotalNetAmountLocalCurrency_Amount = SOURCE.TotalNetAmountLocalCurrency_Amount,
    TARGET.TotalNetAmountLocalCurrency_Currency = SOURCE.TotalNetAmountLocalCurrency_Currency,
    TARGET.TotalAmountWithTaxLocalCurrency_Amount = SOURCE.TotalAmountWithTaxLocalCurrency_Amount,
    TARGET.TotalAmountWithTaxLocalCurrency_Currency = SOURCE.TotalAmountWithTaxLocalCurrency_Currency,
    TARGET.TotalProfitAmount_Amount = SOURCE.TotalProfitAmount_Amount,
    TARGET.TotalProfitAmount_Currency = SOURCE.TotalProfitAmount_Currency,

    TARGET.NetSubTotalAlternativeCurrency_Amount = SOURCE.NetSubTotalAlternativeCurrency_Amount,
    TARGET.NetSubTotalAlternativeCurrency_Currency = SOURCE.NetSubTotalAlternativeCurrency_Currency,
    TARGET.TotalNetAmountAlternativeCurrency_Amount = SOURCE.TotalNetAmountAlternativeCurrency_Amount,
    TARGET.TotalNetAmountAlternativeCurrency_Currency = SOURCE.TotalNetAmountAlternativeCurrency_Currency,
    TARGET.TotalAmountWithTaxAlternativeCurrency_Amount = SOURCE.TotalAmountWithTaxAlternativeCurrency_Amount,
    TARGET.TotalAmountWithTaxAlternativeCurrency_Currency = SOURCE.TotalAmountWithTaxAlternativeCurrency_Currency,
    TARGET.TotalProfitAmountAlternativeCurrency_Amount = SOURCE.TotalProfitAmountAlternativeCurrency_Amount,
    TARGET.TotalProfitAmountAlternativeCurrency_Currency = SOURCE.TotalProfitAmountAlternativeCurrency_Currency,

    TARGET.ReferenceCode = SOURCE.ReferenceCode,
    TARGET.InRefCode = SOURCE.InRefCode,
    TARGET.CustomerOrderNumber = SOURCE.CustomerOrderNumber,
    TARGET.TPOutReferenceCode = SOURCE.TPOutReferenceCode,
    TARGET.SAPOutReferenceCode = SOURCE.SAPOutReferenceCode,
    TARGET.ItemNo = SOURCE.ItemNo,
    TARGET.CrmOrderNotes = SOURCE.CrmOrderNotes,
    TARGET.Name = SOURCE.Name,
    TARGET.SerialNumber = SOURCE.SerialNumber,

    TARGET._SyncedAt = GETUTCDATE()

WHEN NOT MATCHED THEN
INSERT (
    Id, QuoteId, AccountId, ProposalOwnerId, WarehouseId, TeamId,
    TeamCreatedById, CompanyId, StockId, SpecialCodeId,
    DistributionChannelSapId, DivisionSapId, SalesDocumentTypeSapId,
    SalesOrganizationSapId, SalesPaymentTermSapId, CrmSalesOfficeSapId,
    CurrencySapId, SalesGroupSapId, ContractId,
    PaymentType, PaymentTypeTime, DeliveryType, DeliveryTypeTime,
    SubTotalAlternativeCurrency, SubTotalDiscountType, Status,
    IsVATExempt, IsEligibleForNetsisIntegration,
    IsEligibleForSapIntegration, IsDeletedFromBackend,
    ExpirationDate, DeliveryDate, CreateOrderDate,
    PlannedInvoiceDate, InvoiceDate,
    SubTotalDiscount, DeliveryTime, PaymentTime,
    AlternativeCurrencyRate, SubTotalDiscountAmount,
    TotalDiscountRate,
    NetSubTotalLocalCurrency_Amount,
    NetSubTotalLocalCurrency_Currency,
    TotalNetAmountLocalCurrency_Amount,
    TotalNetAmountLocalCurrency_Currency,
    TotalAmountWithTaxLocalCurrency_Amount,
    TotalAmountWithTaxLocalCurrency_Currency,
    TotalProfitAmount_Amount,
    TotalProfitAmount_Currency,
    NetSubTotalAlternativeCurrency_Amount,
    NetSubTotalAlternativeCurrency_Currency,
    TotalNetAmountAlternativeCurrency_Amount,
    TotalNetAmountAlternativeCurrency_Currency,
    TotalAmountWithTaxAlternativeCurrency_Amount,
    TotalAmountWithTaxAlternativeCurrency_Currency,
    TotalProfitAmountAlternativeCurrency_Amount,
    TotalProfitAmountAlternativeCurrency_Currency,
    ReferenceCode, InRefCode, CustomerOrderNumber,
    TPOutReferenceCode, SAPOutReferenceCode,
    ItemNo, CrmOrderNotes, Name, SerialNumber, _SyncedAt
)
VALUES (
    SOURCE.Id, SOURCE.QuoteId, SOURCE.AccountId,
    SOURCE.ProposalOwnerId, SOURCE.WarehouseId,
    SOURCE.TeamId, SOURCE.TeamCreatedById,
    SOURCE.CompanyId, SOURCE.StockId,
    SOURCE.SpecialCodeId,
    SOURCE.DistributionChannelSapId,
    SOURCE.DivisionSapId,
    SOURCE.SalesDocumentTypeSapId,
    SOURCE.SalesOrganizationSapId,
    SOURCE.SalesPaymentTermSapId,
    SOURCE.CrmSalesOfficeSapId,
    SOURCE.CurrencySapId,
    SOURCE.SalesGroupSapId,
    SOURCE.ContractId,
    SOURCE.PaymentType, SOURCE.PaymentTypeTime,
    SOURCE.DeliveryType, SOURCE.DeliveryTypeTime,
    SOURCE.SubTotalAlternativeCurrency,
    SOURCE.SubTotalDiscountType,
    SOURCE.Status,
    SOURCE.IsVATExempt,
    SOURCE.IsEligibleForNetsisIntegration,
    SOURCE.IsEligibleForSapIntegration,
    SOURCE.IsDeletedFromBackend,
    SOURCE.ExpirationDate,
    SOURCE.DeliveryDate,
    SOURCE.CreateOrderDate,
    SOURCE.PlannedInvoiceDate,
    SOURCE.InvoiceDate,
    SOURCE.SubTotalDiscount,
    SOURCE.DeliveryTime,
    SOURCE.PaymentTime,
    SOURCE.AlternativeCurrencyRate,
    SOURCE.SubTotalDiscountAmount,
    SOURCE.TotalDiscountRate,
    SOURCE.NetSubTotalLocalCurrency_Amount,
    SOURCE.NetSubTotalLocalCurrency_Currency,
    SOURCE.TotalNetAmountLocalCurrency_Amount,
    SOURCE.TotalNetAmountLocalCurrency_Currency,
    SOURCE.TotalAmountWithTaxLocalCurrency_Amount,
    SOURCE.TotalAmountWithTaxLocalCurrency_Currency,
    SOURCE.TotalProfitAmount_Amount,
    SOURCE.TotalProfitAmount_Currency,
    SOURCE.NetSubTotalAlternativeCurrency_Amount,
    SOURCE.NetSubTotalAlternativeCurrency_Currency,
    SOURCE.TotalNetAmountAlternativeCurrency_Amount,
    SOURCE.TotalNetAmountAlternativeCurrency_Currency,
    SOURCE.TotalAmountWithTaxAlternativeCurrency_Amount,
    SOURCE.TotalAmountWithTaxAlternativeCurrency_Currency,
    SOURCE.TotalProfitAmountAlternativeCurrency_Amount,
    SOURCE.TotalProfitAmountAlternativeCurrency_Currency,
    SOURCE.ReferenceCode,
    SOURCE.InRefCode,
    SOURCE.CustomerOrderNumber,
    SOURCE.TPOutReferenceCode,
    SOURCE.SAPOutReferenceCode,
    SOURCE.ItemNo,
    SOURCE.CrmOrderNotes,
    SOURCE.Name,
    SOURCE.SerialNumber,
    GETUTCDATE()
);
