MERGE [ParamCrm_Cockpit].[dbo].[Person] AS TARGET
USING (
    SELECT
        CAST(Id AS nvarchar(450)) AS Id,
        Name,
        SurName,
        Title,
        Email,
        CellPhone,
        Phone,
        CAST(EmploymentDate AS date) AS EmploymentDate,
        CAST(EndOfEmploymentDate AS date) AS EndOfEmploymentDate,
        UserName,
        IdentificationNumber,
        Nationality,
        CAST(BirthDate AS date) AS BirthDate,
        Gender,
        MaritalStatus,
        NumberOfChildren,
        BloodType,
        Height,
        Weight,
        Size,
        ShoeSize,
        CAST(ManagerId AS nvarchar(max)) AS ManagerId,
        Status,
        CAST(DealerId AS nvarchar(max)) AS DealerId,
        CAST(RoleId AS nvarchar(max)) AS RoleId,
        MaxDiscountRate,
        CAST(CompanyId AS nvarchar(max)) AS CompanyId,
        PersonNameSurname,
        ManagerType,
        PlaCod,
        AddressInfo_City,
        AddressInfo_District AS AddressInfo_Town,
        AddressInfo_Address AS AddressInfo_AddressLine,
        AddressInfo_PostalCode,
        AddressInfo_CountryCode AS AddressInfo_Country
    FROM [1886662b0a1847a7973577f52892968fdb].[dbo].[Person]
    WHERE DeletedOn IS NULL And CompanyId = '4f1687e4-f282-4601-a3cc-ef612e00c3e4'
) AS SOURCE
ON TARGET.Id = SOURCE.Id COLLATE Turkish_CI_AS
WHEN NOT MATCHED BY SOURCE THEN
    DELETE
WHEN MATCHED THEN
UPDATE SET
    TARGET.Name = SOURCE.Name,
    TARGET.SurName = SOURCE.SurName,
    TARGET.Title = SOURCE.Title,
    TARGET.Email = SOURCE.Email,
    TARGET.CellPhone = SOURCE.CellPhone,
    TARGET.Phone = SOURCE.Phone,
    TARGET.EmploymentDate = SOURCE.EmploymentDate,
    TARGET.EndOfEmploymentDate = SOURCE.EndOfEmploymentDate,
    TARGET.UserName = SOURCE.UserName,
    TARGET.IdentificationNumber = SOURCE.IdentificationNumber,
    TARGET.Nationality = SOURCE.Nationality,
    TARGET.BirthDate = SOURCE.BirthDate,
    TARGET.Gender = SOURCE.Gender,
    TARGET.MaritalStatus = SOURCE.MaritalStatus,
    TARGET.NumberOfChildren = SOURCE.NumberOfChildren,
    TARGET.BloodType = SOURCE.BloodType,
    TARGET.Height = SOURCE.Height,
    TARGET.Weight = SOURCE.Weight,
    TARGET.Size = SOURCE.Size,
    TARGET.ShoeSize = SOURCE.ShoeSize,
    TARGET.ManagerId = SOURCE.ManagerId,
    TARGET.Status = SOURCE.Status,
    TARGET.DealerId = SOURCE.DealerId,
    TARGET.RoleId = SOURCE.RoleId,
    TARGET.MaxDiscountRate = SOURCE.MaxDiscountRate,
    TARGET.CompanyId = SOURCE.CompanyId,
    TARGET.PersonNameSurname = SOURCE.PersonNameSurname,
    TARGET.ManagerType = SOURCE.ManagerType,
    TARGET.PlaCod = SOURCE.PlaCod,
    TARGET.AddressInfo_City = SOURCE.AddressInfo_City,
    TARGET.AddressInfo_Town = SOURCE.AddressInfo_Town,
    TARGET.AddressInfo_AddressLine = SOURCE.AddressInfo_AddressLine,
    TARGET.AddressInfo_PostalCode = SOURCE.AddressInfo_PostalCode,
    TARGET.AddressInfo_Country = SOURCE.AddressInfo_Country,
    TARGET._SyncedAt = GETUTCDATE()

WHEN NOT MATCHED THEN
INSERT (
    Id, Name, SurName, Title, Email, CellPhone, Phone,
    EmploymentDate, EndOfEmploymentDate, UserName,
    IdentificationNumber, Nationality, BirthDate,
    Gender, MaritalStatus, NumberOfChildren, BloodType,
    Height, Weight, Size, ShoeSize,
    ManagerId, Status, DealerId, RoleId,
    MaxDiscountRate, CompanyId, PersonNameSurname,
    ManagerType, PlaCod,
    AddressInfo_City, AddressInfo_Town,
    AddressInfo_AddressLine, AddressInfo_PostalCode,
    AddressInfo_Country, _SyncedAt
)
VALUES (
    SOURCE.Id, SOURCE.Name, SOURCE.SurName, SOURCE.Title,
    SOURCE.Email, SOURCE.CellPhone, SOURCE.Phone,
    SOURCE.EmploymentDate, SOURCE.EndOfEmploymentDate,
    SOURCE.UserName, SOURCE.IdentificationNumber,
    SOURCE.Nationality, SOURCE.BirthDate,
    SOURCE.Gender, SOURCE.MaritalStatus,
    SOURCE.NumberOfChildren, SOURCE.BloodType,
    SOURCE.Height, SOURCE.Weight,
    SOURCE.Size, SOURCE.ShoeSize,
    SOURCE.ManagerId, SOURCE.Status,
    SOURCE.DealerId, SOURCE.RoleId,
    SOURCE.MaxDiscountRate, SOURCE.CompanyId,
    SOURCE.PersonNameSurname, SOURCE.ManagerType,
    SOURCE.PlaCod,
    SOURCE.AddressInfo_City,
    SOURCE.AddressInfo_Town,
    SOURCE.AddressInfo_AddressLine,
    SOURCE.AddressInfo_PostalCode,
    SOURCE.AddressInfo_Country,
    GETUTCDATE()
);