USE [ParamCrm_Cockpit]
GO

MERGE INTO [dbo].[Quote] AS TARGET
USING (
    SELECT
        CAST([Id] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [Id],
        CAST([OpportunityId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [OpportunityId],
        CAST([RevisionId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [RevisionId],
        CAST([Number] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [Number],
        CAST([Name] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [Name],
        CONVERT(nvarchar(450), [ExpirationDate], 126) COLLATE Turkish_CI_AS AS [ExpirationDate],
        CAST([SubTotalDiscount] AS float) AS [SubTotalDiscount],
        CAST([WarehouseId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [WarehouseId],
        CAST([ProposalOwnerId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [ProposalOwnerId],
        [PaymentType],
        [PaymentTypeTime],
        [Status],
        CAST([AddressIdentifier] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [AddressIdentifier],
        [DeliveryType],
        [DeliveryTime],
        CONVERT(nvarchar(450), [DeliveryDate], 126) COLLATE Turkish_CI_AS AS [DeliveryDate],
        CAST([CustomerOrderNumber] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [CustomerOrderNumber],
        [PaymentTime],
        [DeliveryTypeTime],
        CAST([PersonId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [PersonId],
        CAST([SpecialCodeId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [SpecialCodeId],
        CAST([AccountId] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [AccountId],
        CAST([Description] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [Description],
        [RevNo],
        CAST([NetSubTotalLocalCurrency_Amount] AS float) AS [NetSubTotalLocalCurrency_Amount],
        CAST([NetSubTotalLocalCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [NetSubTotalLocalCurrency_Currency],
        CAST([TotalNetAmountLocalCurrency_Amount] AS float) AS [TotalNetAmountLocalCurrency_Amount],
        CAST([TotalNetAmountLocalCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalNetAmountLocalCurrency_Currency],
        CAST([TotalAmountWithTaxLocalCurrency_Amount] AS float) AS [TotalAmountWithTaxLocalCurrency_Amount],
        CAST([TotalAmountWithTaxLocalCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalAmountWithTaxLocalCurrency_Currency],
        CAST([TotalProfitAmount_Amount] AS float) AS [TotalProfitAmount_Amount],
        CAST([TotalProfitAmount_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalProfitAmount_Currency],
        [RevStatus],
        [SubTotalAlternativeCurrency],
        CAST([AlternativeCurrencyRate] AS float) AS [AlternativeCurrencyRate],
        CAST([NetSubTotalAlternativeCurrency_Amount] AS float) AS [NetSubTotalAlternativeCurrency_Amount],
        CAST([NetSubTotalAlternativeCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [NetSubTotalAlternativeCurrency_Currency],
        CAST([TotalNetAmountAlternativeCurrency_Amount] AS float) AS [TotalNetAmountAlternativeCurrency_Amount],
        CAST([TotalNetAmountAlternativeCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalNetAmountAlternativeCurrency_Currency],
        CAST([TotalAmountWithTaxAlternativeCurrency_Amount] AS float) AS [TotalAmountWithTaxAlternativeCurrency_Amount],
        CAST([TotalAmountWithTaxAlternativeCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalAmountWithTaxAlternativeCurrency_Currency],
        CAST([TotalProfitAmountAlternativeCurrency_Amount] AS float) AS [TotalProfitAmountAlternativeCurrency_Amount],
        CAST([TotalProfitAmountAlternativeCurrency_Currency] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TotalProfitAmountAlternativeCurrency_Currency],
        CAST([IsVATExempt] AS int) AS [IsVATExempt],
        CAST([TermsAndConditions] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TermsAndConditions],
        CAST([ProductsAndServices] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [ProductsAndServices],
        CONVERT(nvarchar(450), [ServiceStartDate], 126) COLLATE Turkish_CI_AS AS [ServiceStartDate],
        CONVERT(nvarchar(450), [ServiceFinishDate], 126) COLLATE Turkish_CI_AS AS [ServiceFinishDate],
        CAST([ReferenceCode] AS nvarchar(450)) COLLATE Turkish_CI_AS AS [ReferenceCode],
        CAST([TransferWithForeignCurrency] AS int) AS [TransferWithForeignCurrency],
        CAST([ContactId] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [ContactId],
        CAST([FirstCreatedDate] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [FirstCreatedDate],
        CAST([FirstCreatedByName] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [FirstCreatedByName],
        CAST([TeamId] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TeamId],
        CAST([TeamCreatedById] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TeamCreatedById],
        [SubTotalDiscountType],
        [SubTotalDiscountAmount],
        CAST([InRefCode] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [InRefCode],
        CAST([CompanyId] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [CompanyId],
        [QuoteApprovalProcessStatus],
        [TotalDiscountRate],
        CAST([FirstReleaseDate] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [FirstReleaseDate],
        CAST([RevisedDate] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [RevisedDate],
        [CRMRevNo],
        CAST([PublicationSource] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [PublicationSource],
        CAST([TermsAndConditions2] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TermsAndConditions2],
        CAST([ProductsAndServices2] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [ProductsAndServices2],
        CAST([StockId] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [StockId],
        CAST([ItemNo] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [ItemNo],
        [QuoteType],
        CAST([CrmOrderId] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [CrmOrderId],
        [OrderWillBeCreate],
        [OrderOwnerWillBeChanged],
        CAST([TPOutReferenceCode] AS nvarchar(max)) COLLATE Turkish_CI_AS AS [TPOutReferenceCode],
        GETUTCDATE() AS [_SyncedAt],
		CreatedOn As [CreatedOn]
    FROM [1886662b0a1847a7973577f52892968fdb].[dbo].[Quote]
    WHERE CompanyId = '4f1687e4-f282-4601-a3cc-ef612e00c3e4' and DeletedOn Is Null
) AS SOURCE
ON TARGET.[Id] COLLATE Turkish_CI_AS = SOURCE.[Id] COLLATE Turkish_CI_AS
WHEN MATCHED THEN
    UPDATE SET
        TARGET.OpportunityId = SOURCE.OpportunityId,
        TARGET.RevisionId = SOURCE.RevisionId,
        TARGET.Number = SOURCE.Number,
        TARGET.Name = SOURCE.Name,
        TARGET.ExpirationDate = SOURCE.ExpirationDate,
        TARGET.SubTotalDiscount = SOURCE.SubTotalDiscount,
        TARGET.WarehouseId = SOURCE.WarehouseId,
        TARGET.ProposalOwnerId = SOURCE.ProposalOwnerId,
        TARGET.PaymentType = SOURCE.PaymentType,
        TARGET.PaymentTypeTime = SOURCE.PaymentTypeTime,
        TARGET.Status = SOURCE.Status,
        TARGET.AddressIdentifier = SOURCE.AddressIdentifier,
        TARGET.DeliveryType = SOURCE.DeliveryType,
        TARGET.DeliveryTime = SOURCE.DeliveryTime,
        TARGET.DeliveryDate = SOURCE.DeliveryDate,
        TARGET.CustomerOrderNumber = SOURCE.CustomerOrderNumber,
        TARGET.PaymentTime = SOURCE.PaymentTime,
        TARGET.PersonId = SOURCE.PersonId,
        TARGET.SpecialCodeId = SOURCE.SpecialCodeId,
        TARGET.AccountId = SOURCE.AccountId,
        TARGET.Description = SOURCE.Description,
        TARGET.RevNo = SOURCE.RevNo,
        TARGET.NetSubTotalLocalCurrency_Amount = SOURCE.NetSubTotalLocalCurrency_Amount,
        TARGET.NetSubTotalLocalCurrency_Currency = SOURCE.NetSubTotalLocalCurrency_Currency,
        TARGET.TotalNetAmountLocalCurrency_Amount = SOURCE.TotalNetAmountLocalCurrency_Amount,
        TARGET.TotalNetAmountLocalCurrency_Currency = SOURCE.TotalNetAmountLocalCurrency_Currency,
        TARGET.TotalAmountWithTaxLocalCurrency_Amount = SOURCE.TotalAmountWithTaxLocalCurrency_Amount,
        TARGET.TotalAmountWithTaxLocalCurrency_Currency = SOURCE.TotalAmountWithTaxLocalCurrency_Currency,
        TARGET.TotalProfitAmount_Amount = SOURCE.TotalProfitAmount_Amount,
        TARGET.TotalProfitAmount_Currency = SOURCE.TotalProfitAmount_Currency,
        TARGET.RevStatus = SOURCE.RevStatus,
        TARGET.SubTotalAlternativeCurrency = SOURCE.SubTotalAlternativeCurrency,
        TARGET.AlternativeCurrencyRate = SOURCE.AlternativeCurrencyRate,
        TARGET.NetSubTotalAlternativeCurrency_Amount = SOURCE.NetSubTotalAlternativeCurrency_Amount,
        TARGET.NetSubTotalAlternativeCurrency_Currency = SOURCE.NetSubTotalAlternativeCurrency_Currency,
        TARGET.TotalNetAmountAlternativeCurrency_Amount = SOURCE.TotalNetAmountAlternativeCurrency_Amount,
        TARGET.TotalNetAmountAlternativeCurrency_Currency = SOURCE.TotalNetAmountAlternativeCurrency_Currency,
        TARGET.TotalAmountWithTaxAlternativeCurrency_Amount = SOURCE.TotalAmountWithTaxAlternativeCurrency_Amount,
        TARGET.TotalAmountWithTaxAlternativeCurrency_Currency = SOURCE.TotalAmountWithTaxAlternativeCurrency_Currency,
        TARGET.TotalProfitAmountAlternativeCurrency_Amount = SOURCE.TotalProfitAmountAlternativeCurrency_Amount,
        TARGET.TotalProfitAmountAlternativeCurrency_Currency = SOURCE.TotalProfitAmountAlternativeCurrency_Currency,
        TARGET.IsVATExempt = SOURCE.IsVATExempt,
        TARGET.TermsAndConditions = SOURCE.TermsAndConditions,
        TARGET.ProductsAndServices = SOURCE.ProductsAndServices,
        TARGET.ServiceStartDate = SOURCE.ServiceStartDate,
        TARGET.ServiceFinishDate = SOURCE.ServiceFinishDate,
        TARGET.ReferenceCode = SOURCE.ReferenceCode,
        TARGET.TransferWithForeignCurrency = SOURCE.TransferWithForeignCurrency,
        TARGET.ContactId = SOURCE.ContactId,
        TARGET.FirstCreatedDate = SOURCE.FirstCreatedDate,
        TARGET.FirstCreatedByName = SOURCE.FirstCreatedByName,
        TARGET.TeamId = SOURCE.TeamId,
        TARGET.TeamCreatedById = SOURCE.TeamCreatedById,
        TARGET.SubTotalDiscountType = SOURCE.SubTotalDiscountType,
        TARGET.SubTotalDiscountAmount = SOURCE.SubTotalDiscountAmount,
        TARGET.InRefCode = SOURCE.InRefCode,
        TARGET.CompanyId = SOURCE.CompanyId,
        TARGET.QuoteApprovalProcessStatus = SOURCE.QuoteApprovalProcessStatus,
        TARGET.TotalDiscountRate = SOURCE.TotalDiscountRate,
        TARGET.FirstReleaseDate = SOURCE.FirstReleaseDate,
        TARGET.RevisedDate = SOURCE.RevisedDate,
        TARGET.CRMRevNo = SOURCE.CRMRevNo,
        TARGET.PublicationSource = SOURCE.PublicationSource,
        TARGET.TermsAndConditions2 = SOURCE.TermsAndConditions2,
        TARGET.ProductsAndServices2 = SOURCE.ProductsAndServices2,
        TARGET.StockId = SOURCE.StockId,
        TARGET.ItemNo = SOURCE.ItemNo,
        TARGET.QuoteType = SOURCE.QuoteType,
        TARGET.CrmOrderId = SOURCE.CrmOrderId,
        TARGET.OrderWillBeCreate = SOURCE.OrderWillBeCreate,
        TARGET.OrderOwnerWillBeChanged = SOURCE.OrderOwnerWillBeChanged,
        TARGET.TPOutReferenceCode = SOURCE.TPOutReferenceCode,
        TARGET._SyncedAt = SOURCE._SyncedAt,
		TARGET.CreatedOn = SOURCE.CreatedOn
WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        Id, OpportunityId, RevisionId, Number, Name, ExpirationDate, SubTotalDiscount, WarehouseId, ProposalOwnerId, PaymentType, 
        PaymentTypeTime, Status, AddressIdentifier, DeliveryType, DeliveryTime, DeliveryDate, CustomerOrderNumber, PaymentTime,
        PersonId, SpecialCodeId, AccountId, Description, RevNo, NetSubTotalLocalCurrency_Amount, NetSubTotalLocalCurrency_Currency,
        TotalNetAmountLocalCurrency_Amount, TotalNetAmountLocalCurrency_Currency, TotalAmountWithTaxLocalCurrency_Amount,
        TotalAmountWithTaxLocalCurrency_Currency, TotalProfitAmount_Amount, TotalProfitAmount_Currency, RevStatus, SubTotalAlternativeCurrency,
        AlternativeCurrencyRate, NetSubTotalAlternativeCurrency_Amount, NetSubTotalAlternativeCurrency_Currency,
        TotalNetAmountAlternativeCurrency_Amount, TotalNetAmountAlternativeCurrency_Currency, TotalAmountWithTaxAlternativeCurrency_Amount,
        TotalAmountWithTaxAlternativeCurrency_Currency, TotalProfitAmountAlternativeCurrency_Amount, TotalProfitAmountAlternativeCurrency_Currency,
        IsVATExempt, TermsAndConditions, ProductsAndServices, ServiceStartDate, ServiceFinishDate, ReferenceCode, TransferWithForeignCurrency,
        ContactId, FirstCreatedDate, FirstCreatedByName, TeamId, TeamCreatedById, SubTotalDiscountType, SubTotalDiscountAmount, InRefCode,
        CompanyId, QuoteApprovalProcessStatus, TotalDiscountRate, FirstReleaseDate, RevisedDate, CRMRevNo, PublicationSource,
        TermsAndConditions2, ProductsAndServices2, StockId, ItemNo, QuoteType, CrmOrderId, OrderWillBeCreate, OrderOwnerWillBeChanged,
        TPOutReferenceCode, _SyncedAt, CreatedOn
    )
    VALUES (
        SOURCE.Id, SOURCE.OpportunityId, SOURCE.RevisionId, SOURCE.Number, SOURCE.Name, SOURCE.ExpirationDate, SOURCE.SubTotalDiscount,
        SOURCE.WarehouseId, SOURCE.ProposalOwnerId, SOURCE.PaymentType, SOURCE.PaymentTypeTime, SOURCE.Status, SOURCE.AddressIdentifier,
        SOURCE.DeliveryType, SOURCE.DeliveryTime, SOURCE.DeliveryDate, SOURCE.CustomerOrderNumber, SOURCE.PaymentTime, SOURCE.PersonId,
        SOURCE.SpecialCodeId, SOURCE.AccountId, SOURCE.Description, SOURCE.RevNo, SOURCE.NetSubTotalLocalCurrency_Amount,
        SOURCE.NetSubTotalLocalCurrency_Currency, SOURCE.TotalNetAmountLocalCurrency_Amount, SOURCE.TotalNetAmountLocalCurrency_Currency,
        SOURCE.TotalAmountWithTaxLocalCurrency_Amount, SOURCE.TotalAmountWithTaxLocalCurrency_Currency, SOURCE.TotalProfitAmount_Amount,
        SOURCE.TotalProfitAmount_Currency, SOURCE.RevStatus, SOURCE.SubTotalAlternativeCurrency, SOURCE.AlternativeCurrencyRate,
        SOURCE.NetSubTotalAlternativeCurrency_Amount, SOURCE.NetSubTotalAlternativeCurrency_Currency, SOURCE.TotalNetAmountAlternativeCurrency_Amount,
        SOURCE.TotalNetAmountAlternativeCurrency_Currency, SOURCE.TotalAmountWithTaxAlternativeCurrency_Amount, SOURCE.TotalAmountWithTaxAlternativeCurrency_Currency,
        SOURCE.TotalProfitAmountAlternativeCurrency_Amount, SOURCE.TotalProfitAmountAlternativeCurrency_Currency, SOURCE.IsVATExempt,
        SOURCE.TermsAndConditions, SOURCE.ProductsAndServices, SOURCE.ServiceStartDate, SOURCE.ServiceFinishDate, SOURCE.ReferenceCode,
        SOURCE.TransferWithForeignCurrency, SOURCE.ContactId, SOURCE.FirstCreatedDate, SOURCE.FirstCreatedByName, SOURCE.TeamId,
        SOURCE.TeamCreatedById, SOURCE.SubTotalDiscountType, SOURCE.SubTotalDiscountAmount, SOURCE.InRefCode, SOURCE.CompanyId,
        SOURCE.QuoteApprovalProcessStatus, SOURCE.TotalDiscountRate, SOURCE.FirstReleaseDate, SOURCE.RevisedDate, SOURCE.CRMRevNo,
        SOURCE.PublicationSource, SOURCE.TermsAndConditions2, SOURCE.ProductsAndServices2, SOURCE.StockId, SOURCE.ItemNo,
        SOURCE.QuoteType, SOURCE.CrmOrderId, SOURCE.OrderWillBeCreate, SOURCE.OrderOwnerWillBeChanged, SOURCE.TPOutReferenceCode,
        SOURCE._SyncedAt, SOURCE.CreatedOn
    );
GO
